vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|07 Dec 2013 07:11:50 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|Admin-VAIO\\Admin
vti_modifiedby:SR|Admin-VAIO\\Admin
vti_timecreated:TR|07 Dec 2013 07:11:50 -0000
vti_cacheddtm:TX|07 Dec 2013 07:11:50 -0000
vti_filesize:IR|7254
vti_cachedtitle:SR|Victor Lin Real Estate Photography Portfolio
vti_cachedbodystyle:SR|<body id="header_small">
vti_cachedlinkinfo:VX|H|/favicon.ico Q|../css/master.css Q|../css/site.css S|https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js S|../js/jquery.lightbox-0.5.js S|../js/jquery.newsslider.js S|http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js S|/js/slides.min.jquery.js I|../includes/slideshowrealestate.inc.php I|../includes/navrealestate.inc.php H|http://www.tourbuzz.net/public/vtour/display/96802 S|../images/links/vtour1.JPG H|http://www.tourbuzz.net/public/vtour/display/97129 S|../images/links/vtour2.JPG H|http://www.tourbuzz.net/public/vtour/display/97518 S|../images/links/vtour3.JPG H|http://www.tourbuzz.net/public/vtour/display/95556 S|../images/links/vtour4.JPG S|../images/lightbox/title_enlargethumb_gray.gif K|virtualtours.php S|../images/lightbox/title_previous.gif K|virtualtours.php S|../images/lightbox/title_more.gif I|../includes/footer.inc.php
vti_cachedsvcrellinks:VX|NHUS|/favicon.ico NQUS|file:///E:/Backups/VLP/public_html/css/master.css NQUS|file:///E:/Backups/VLP/public_html/css/site.css NSSS|https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js NSUS|file:///E:/Backups/VLP/public_html/js/jquery.lightbox-0.5.js NSUS|file:///E:/Backups/VLP/public_html/js/jquery.newsslider.js NSHS|http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js NSUS|/js/slides.min.jquery.js NIUS|file:///E:/Backups/VLP/public_html/includes/slideshowrealestate.inc.php NIUS|file:///E:/Backups/VLP/public_html/includes/navrealestate.inc.php NHHS|http://www.tourbuzz.net/public/vtour/display/96802 NSUS|file:///E:/Backups/VLP/public_html/images/links/vtour1.JPG NHHS|http://www.tourbuzz.net/public/vtour/display/97129 NSUS|file:///E:/Backups/VLP/public_html/images/links/vtour2.JPG NHHS|http://www.tourbuzz.net/public/vtour/display/97518 NSUS|file:///E:/Backups/VLP/public_html/images/links/vtour3.JPG NHHS|http://www.tourbuzz.net/public/vtour/display/95556 NSUS|file:///E:/Backups/VLP/public_html/images/links/vtour4.JPG NSUS|file:///E:/Backups/VLP/public_html/images/lightbox/title_enlargethumb_gray.gif FKUS|virtualtours.php NSUS|file:///E:/Backups/VLP/public_html/images/lightbox/title_previous.gif FKUS|virtualtours.php NSUS|file:///E:/Backups/VLP/public_html/images/lightbox/title_more.gif NIUS|file:///E:/Backups/VLP/public_html/includes/footer.inc.php
vti_cachedneedsrewrite:BR|true
vti_cachedhasbots:BR|true
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1 keywords victor\\ lin,\\ real\\ estate\\ photographer\\ california,\\ real\\ estate\\ photographer\\ Fremont,\\ real\\ estate\\ photographer\\ San\\ Francisco,\\ real\\ estate\\ photographer\\ San\\ Jose,\\ real\\ estate\\ photographer\\ Mountain\\ View,\\ real\\ estate\\ photographer\\ Palo\\ Alto,\\ real\\ estate\\ photographer\\ Cupertino,\\ real\\ estate\\ photographer\\ Los\\ Altos,\\ real\\ estate\\ photographer\\ Sunnyvale,\\ real\\ estate\\ photographer\\ Milpitas,\\ real\\ estate\\ photographer\\ Santa\\ Clara,\\ real\\ estate\\ photographer\\ Saratoga,\\ real\\ estate\\ photographer\\ Menlo\\ Park,\\ real\\ estate\\ photographer\\ San\\ Carlos,\\ real\\ estate\\ photographer\\ Redwood\\ City,\\ real\\ estate\\ photographer\\ San\\ Mateo,\\ real\\ estate\\ photographer\\ Campbell,\\ real\\ estate\\ photographer\\ Union\\ City,\\ real\\ estate\\ photographer\\ Hayward,\\ real\\ estate\\ photographer\\ Los\\ Gatos. description Photography\\ in\\ California\\ from\\ Victor\\ Lin\\ Photography\\ covers\\ photography\\ in\\ Fremont,\\ San\\ Francisco,\\ San\\ Jose,\\ Mountain\\ View,\\ Palo\\ Alto,\\ Cupertino,\\ Los\\ Altos,\\ Sunnyvale,\\ Milpitas,\\ Santa\\ Clara,\\ Saratoga,\\ Menlo\\ Park,\\ San\\ Carlos,\\ Redwood\\ City,\\ San\\ Mateo,\\ Campbell,\\ Union\\ City,\\ Hayward,\\ and\\ Los\\ Gatos.
vti_charset:SR|iso-8859-1
vti_title:SR|Victor Lin Real Estate Photography Portfolio
vti_backlinkinfo:VX|index.php virtualtours.php
