vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|26 Apr 2013 04:40:18 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|Admin-VAIO\\Admin
vti_modifiedby:SR|Admin-VAIO\\Admin
vti_timecreated:TR|26 Apr 2013 04:40:18 -0000
vti_cacheddtm:TX|12 Mar 2014 06:43:57 -0000
vti_filesize:IR|9341
vti_cachedtitle:SR|Victor Lin Real Estate Photography
vti_cachedbodystyle:SR|<body id="header_big">
vti_cachedlinkinfo:VX|H|/favicon.ico Q|../css/master.css Q|../css/site.css S|https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js S|../js/jquery.lightbox-0.5.js S|../js/jquery.newsslider.js S|http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js S|/js/slides.min.jquery.js I|../includes/slideshowrealestate.inc.php I|../includes/navrealestate.inc.php H|http://onetwosixdesign.com/ H|http://onetwosixdesign.com/ H|http://www.redfin.com/CA/Santa-Clara/4337-Watson-Cir-95054/home/1261303 H|http://www.redfin.com/CA/Santa-Clara/4337-Watson-Cir-95054/home/1261303 H|http://www.irisho.com/ H|http://www.aicare.com/index.html H|http://www.aicare.com/index.html H|http://www.realestaterain.com/about H|http://www.realestaterain.com/ H|http://www.realestaterain.com/ H|http://www.californiamoves.com/agentoffice/agentdetail.aspx H|http://www.californiamoves.com/agentoffice/agentdetail.aspx H|http://agent.interorealestate.com/splash.aspx H|http://agent.interorealestate.com/splash.aspx H|www.saritnetanel.com" H|www.saritnetanel.com" H|http://www.mxrca.com/AnniePeng/Default.aspx H|http://www.mxrca.com/AnniePeng/Default.aspx H|www.MenloAthertonRealty.com" H|www.MenloAthertonRealty.com" H|www.pacificpeninsula.com" H|www.pacificpeninsula.com" H|www.margokellyhomes.com" H|www.margokellyhomes.com" I|../includes/footer.inc.php
vti_cachedsvcrellinks:VX|NHUS|/favicon.ico NQUS|file:///E:/Backups/VLP/public_html/css/master.css NQUS|file:///E:/Backups/VLP/public_html/css/site.css NSSS|https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js NSUS|file:///E:/Backups/VLP/public_html/js/jquery.lightbox-0.5.js NSUS|file:///E:/Backups/VLP/public_html/js/jquery.newsslider.js NSHS|http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js NSUS|/js/slides.min.jquery.js NIUS|file:///E:/Backups/VLP/public_html/includes/slideshowrealestate.inc.php NIUS|file:///E:/Backups/VLP/public_html/includes/navrealestate.inc.php NHHS|http://onetwosixdesign.com/ NHHS|http://onetwosixdesign.com/ NHHS|http://www.redfin.com/CA/Santa-Clara/4337-Watson-Cir-95054/home/1261303 NHHS|http://www.redfin.com/CA/Santa-Clara/4337-Watson-Cir-95054/home/1261303 NHHS|http://www.irisho.com/ NHHS|http://www.aicare.com/index.html NHHS|http://www.aicare.com/index.html NHHS|http://www.realestaterain.com/about NHHS|http://www.realestaterain.com/ NHHS|http://www.realestaterain.com/ NHHS|http://www.californiamoves.com/agentoffice/agentdetail.aspx NHHS|http://www.californiamoves.com/agentoffice/agentdetail.aspx NHHS|http://agent.interorealestate.com/splash.aspx NHHS|http://agent.interorealestate.com/splash.aspx NHUS|www.saritnetanel.com" NHUS|www.saritnetanel.com" NHHS|http://www.mxrca.com/AnniePeng/Default.aspx NHHS|http://www.mxrca.com/AnniePeng/Default.aspx NHUS|www.MenloAthertonRealty.com" NHUS|www.MenloAthertonRealty.com" NHUS|www.pacificpeninsula.com" NHUS|www.pacificpeninsula.com" NHUS|www.margokellyhomes.com" NHUS|www.margokellyhomes.com" NIUS|file:///E:/Backups/VLP/public_html/includes/footer.inc.php
vti_cachedneedsrewrite:BR|true
vti_cachedhasbots:BR|true
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1 Keywords victor\\ lin,\\ real\\ estate\\ photographer\\ california,\\ real\\ estate\\ photographer\\ Fremont,\\ real\\ estate\\ photographer\\ San\\ Francisco,\\ real\\ estate\\ photographer\\ San\\ Jose,\\ real\\ estate\\ photographer\\ Mountain\\ View,\\ real\\ estate\\ photographer\\ Palo\\ Alto,\\ real\\ estate\\ photographer\\ Cupertino,\\ real\\ estate\\ photographer\\ Los\\ Altos,\\ real\\ estate\\ photographer\\ Sunnyvale,\\ real\\ estate\\ photographer\\ Milpitas,\\ real\\ estate\\ photographer\\ Santa\\ Clara,\\ real\\ estate\\ photographer\\ Saratoga,\\ real\\ estate\\ photographer\\ Menlo\\ Park,\\ real\\ estate\\ photographer\\ San\\ Carlos,\\ real\\ estate\\ photographer\\ Redwood\\ City,\\ real\\ estate\\ photographer\\ San\\ Mateo,\\ real\\ estate\\ photographer\\ Campbell,\\ real\\ estate\\ photographer\\ Union\\ City,\\ real\\ estate\\ photographer\\ Hayward,\\ real\\ estate\\ photographer\\ Los\\ Gatos. Description Photography\\ in\\ California\\ from\\ Victor\\ Lin\\ Photography\\ covers\\ photography\\ in\\ Fremont,\\ San\\ Francisco,\\ San\\ Jose,\\ Mountain\\ View,\\ Palo\\ Alto,\\ Cupertino,\\ Los\\ Altos,\\ Sunnyvale,\\ Milpitas,\\ Santa\\ Clara,\\ Saratoga,\\ Menlo\\ Park,\\ San\\ Carlos,\\ Redwood\\ City,\\ San\\ Mateo,\\ Campbell,\\ Union\\ City,\\ Hayward,\\ and\\ Los\\ Gatos.
vti_charset:SR|iso-8859-1
vti_title:SR|Victor Lin Real Estate Photography
vti_backlinkinfo:VX|index.php
